function createfigure(X1, YMatrix1, X2, YMatrix2)
%CREATEFIGURE(X1,YMATRIX1,X2,YMATRIX2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 05-Jun-2017 16:24:46

% Create figure
figure1 = figure('XVisual',...
    '0x22 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'FontWeight','bold','FontSize',16);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',2,'Color',[0 0 0]);
set(plot1(1),'DisplayName','Ref. Sol.');
set(plot1(2),'LineWidth',4);

% Create multiple lines using matrix input to plot
plot2 = plot(X2,YMatrix2,'Parent',axes1,'LineWidth',2);
set(plot2(1),'Color',[0 0 1],'DisplayName','Harmonic');
set(plot2(2),'Color',[1 0 0],'DisplayName','Arithmetic');
set(plot2(3),'Color',[0 0 1]);
set(plot2(4),'Color',[1 0 0]);

% Create xlabel
xlabel('x','FontWeight','bold','FontSize',16);

% Create ylabel
ylabel('p','FontWeight','bold','FontSize',16);

% Create title
title('Pressure versus position at various times','FontWeight','bold',...
    'FontSize',16);

% Create legend
legend1 = legend('Ref. Sol.', 'Harmonic', 'Arithmetic');
set(legend1,'Location','SouthWest');

% Create textbox
annotation(figure1,'textbox',...
    [0.427518010291594 0.590361445783133 0.152241852487136 0.0687451751214514],...
    'String',{' t = 1.0e-4'},...
    'FontWeight','bold',...
    'FontSize',16,...
    'FitBoxToText','off',...
    'LineWidth',2);

% Create textbox
annotation(figure1,'textbox',...
    [0.644224699828473 0.712564543889845 0.0864785591766725 0.0671256454388993],...
    'String',{' t = 1'},...
    'FontWeight','bold',...
    'FontSize',16,...
    'FitBoxToText','off',...
    'LineWidth',2);

