function createfigure_timepxpxx(X1, Y1, X2, YMatrix1)
%CREATEFIGURE(X1,Y1,X2,YMATRIX1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 13-Jun-2017 20:00:09

% Create figure
figure1 = figure('XVisual',...
    '0x22 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'FontWeight','bold','FontSize',16);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',6,'LineStyle','--',...
    'DisplayName','Ref. Sol.',...
    'Color',[0 0 0]);

% Create multiple lines using matrix input to plot
plot1 = plot(X2,YMatrix1,'Parent',axes1,'LineWidth',4);
set(plot1(1),'LineStyle','-','Color',[0 0 1],...
    'DisplayName',sprintf('Harmonic\n'));
set(plot1(3),'Color',[0.0431372560560703 0.517647087574005 0.780392169952393],'DisplayName','Cancel p_x^4', 'LineWidth', 3);
set(plot1(2),'LineStyle','-.',...
    'Color',[1 0 1],...
    'DisplayName','Cancel p_x^2p_{xx}');
set(plot1(4),'LineStyle',':','Color',[0 0.498039215803146 0],...
    'DisplayName','Cancel both (MHM)');

% Create ylabel
ylabel('p','FontWeight','bold','FontSize',16);

% Create title
title('Solution profile as a function of t','FontWeight','bold',...
    'FontSize',16);

% Create xlabel
xlabel('t','FontWeight','bold','FontSize',16);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','SouthEast');

