function createfigurepm(X1, YMatrix1)
%CREATEFIGURE2(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 07-Jun-2017 23:47:15

% Create figure
figure1 = figure('XVisual',...
    '0x22 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'FontWeight','bold','FontSize',16);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',4);
set(plot1(1),'DisplayName','m = 1');
set(plot1(2),'LineStyle','--','DisplayName','m = 2');
set(plot1(3),'LineStyle',':','DisplayName','m = 3');

% Create xlabel
xlabel('x','FontWeight','bold','FontSize',16);

% Create ylabel
ylabel('p','FontWeight','bold','FontSize',16);

% Create title
title('Solution profile as a function of x','FontWeight','bold',...
    'FontSize',16);

% Create legend
legend(axes1,'show');

