function createfigure_harmtemposcill(X1, Y1)
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 16-Jun-2017 19:15:29

% Create figure
figure1 = figure('XVisual',...
    '0x22 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'XTick',[0.014 0.02 0.026 0.032 0.038],...
    'FontWeight','bold',...
    'FontSize',16);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.014 0.038]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'LineWidth',2);

