function createfigurepos(X1, Y1, X2, YMatrix1)
%CREATEFIGURE(X1,Y1,X2,YMATRIX1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 21-Mar-2017 13:27:39

% Create figure
figure1 = figure('XVisual',...
    '0x22 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'FontWeight','bold','FontSize',16);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'MarkerSize',8,'LineWidth',8,...
    'DisplayName','Ref. Sol.',...
    'Color',[0 0 0]);

% Create multiple lines using matrix input to plot
plot1 = plot(X2,YMatrix1,'Parent',axes1,'MarkerSize',10,'LineWidth',2);
set(plot1(1),'Marker','o','Color',[1 0 0],'DisplayName','Arithmetic');
set(plot1(2),'Marker','^','Color',[0 0 1],...
    'DisplayName','Harmonic');
set(plot1(3),'Marker','square','Color',[0 0.498039215803146 0],...
    'DisplayName','Mod. Harmonic');

% Create xlabel
xlabel('x','FontWeight','bold','FontSize',16);

% Create ylabel
ylabel('p','FontWeight','bold','FontSize',16);

% Create title
title('Pressure vs. position','FontWeight','bold','FontSize',16);

% Create legend
legend(axes1,'show');

