function createfigure_foamamrt(X1, YMatrix1, X2, Y1)
%CREATEFIGURE(X1,YMATRIX1,X2,Y1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 17-May-2017 21:44:25

% Create figure
figure1 = figure('XVisual',...
    '0x22 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'FontWeight','bold','FontSize',16);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.065 0.1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.45 0.6]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',4);
set(plot1(1),'DisplayName','Exact Sol.','Color',[0 0 0]);
set(plot1(2),'DisplayName','Integral');

% Create plot
plot(X2,Y1,'Parent',axes1,'LineWidth',3,'Color',[1 0 1],...
    'DisplayName','AMR Integral');

% Create xlabel
xlabel('t','FontWeight','bold','FontSize',16);

% Create ylabel
ylabel('p','FontWeight','bold','FontSize',16);

% Create title
title('Solution profile as a function of t','FontWeight','bold','FontSize',16);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','NorthWest');

