function createfigure_foamjst(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 08-May-2018 15:02:02

% Create figure
figure1 = figure('XVisual',...
    '0x22 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'FontWeight','bold','FontSize',16);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'MarkerSize',9,'LineWidth',8,'DisplayName','Exact Sol.',...
    'Color',[0 0 0]);
set(plot1(2),'MarkerSize',8,'Marker','<','LineWidth',5,'LineStyle','-.',...
    'Color',[1 0.400000005960464 1],...
    'DisplayName','JST');

% Create xlabel
xlabel('x','FontWeight','bold','FontSize',16);

% Create ylabel
ylabel('p','FontWeight','bold','FontSize',16);

% Create title
title('Solution profile as a function of x','FontWeight','bold',...
    'FontSize',16);

% Create legend
legend(axes1,'show');

