function createfigure_foamjstt(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
 
%  Auto-generated by MATLAB on 17-May-2017 12:24:39
 
% Create figure
figure1 = figure('XVisual',...
'0x22 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');
 
% Create axes
axes1 = axes('Parent',figure1,'FontWeight','bold','FontSize',16);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.065 0.1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.45 0.65]);
box(axes1,'on');
hold(axes1,'all');
 
% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'LineWidth',4,'DisplayName','Exact Sol.','Color',[0 0 0]);
set(plot1(2),'MarkerSize',1,'LineWidth',5,'LineStyle','-.',...
'Color',[1 0.400000005960464 1],...
'DisplayName','JST');
if (length(plot1) > 2)
   set(plot1(3),'MarkerSize',1,'LineWidth',5,'LineStyle','--',...
'Color',[0.39215686917305 0.474509805440903 0.635294139385223],...
'DisplayName','superbee');
set(plot1(4),'MarkerSize',1,'LineWidth',5,'LineStyle',':',...
'DisplayName','van leer');
end
 
% Create xlabel
xlabel('t','FontWeight','bold','FontSize',16);
 
% Create ylabel
ylabel('p','FontWeight','bold','FontSize',16);
 
% Create title
title('Solution profile as a function of t','FontWeight','bold','FontSize',16);
 
% Create legend
legend(axes1,'show');
 
