function createfigure_foamamr(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 17-May-2017 17:54:37

% Create figure
figure1 = figure('XVisual',...
    '0x22 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'FontWeight','bold','FontSize',16);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'MarkerSize',8);
set(plot1(1),'LineWidth',8,'DisplayName','Exact Sol.','Color',[0 0 0]);
set(plot1(2),'Marker','x','LineWidth',5,'LineStyle','-.',...
    'Color',[0 0.498039215803146 0],...
    'DisplayName','Integral');
set(plot1(3),'Marker','square','LineWidth',2,'LineStyle','--',...
    'Color',[1 0 1],...
    'DisplayName','AMR Integral',...
    'MarkerSize',6);

% Create xlabel
xlabel('x','FontWeight','bold','FontSize',16);

% Create ylabel
ylabel('p','FontWeight','bold','FontSize',16);

% Create title
title('Solution profile as a function of x','FontWeight','bold','FontSize',16);

% Create legend
legend(axes1,'show');

