function createfigure(X1, Y1, X2, YMatrix1, X3, Y2)
%CREATEFIGURE(X1,Y1,X2,YMATRIX1,X3,Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  YMATRIX1:  matrix of y data
%  X3:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 05-Jun-2017 19:29:19

% Create figure
figure1 = figure('XVisual',...
    '0x22 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'FontWeight','bold','FontSize',16);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 2]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',2,'DisplayName','Ref. Sol.',...
    'Color',[0 0 0]);

% Create multiple lines using matrix input to plot
plot1 = plot(X2,YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(1),'Color',[0.600000023841858 0.200000002980232 0],...
    'DisplayName',['Backward Euler ',sprintf('\n'),'\Delta t = O(\Delta x^2)']);
set(plot1(2),'Color',[0.749019622802734 0 0.749019622802734],...
    'DisplayName','RK2 TVD');

% Create plot
plot(X3,Y2,'Parent',axes1,'LineWidth',2,...
    'Color',[0.682352960109711 0.466666668653488 0],...
    'DisplayName',['Backward Euler ',sprintf('\n'),'\Delta t = O(\Delta x)']);

% Create xlabel
xlabel('x','FontWeight','bold','FontSize',16);

% Create ylabel
ylabel('p(t, x = 0.12)','FontWeight','bold','FontSize',16);

% Create title
title('Solutions with harmonic averaging and various temporal schemes',...
    'FontWeight','bold',...
    'FontSize',16);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','SouthEast');

