function createfigure_foamtimezoom(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 17-May-2017 10:05:15

% Create figure
figure1 = figure('XVisual',...
    '0x22 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'FontWeight','bold','FontSize',16);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0.45 0.65]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',4);
set(plot1(1),'DisplayName','Exact Sol.','Color',[0 0 0]);
set(plot1(2),'MarkerSize',1,'LineWidth',3,'LineStyle','-.','Color',[1 0 0],...
    'DisplayName','Arithmetic');
set(plot1(3),'LineStyle',':','Color',[0 0 1],'DisplayName','Harmonic');

% Create xlabel
xlabel('t','FontWeight','bold','FontSize',16);

% Create ylabel
ylabel('p(t, x = 0.32)','FontWeight','bold','FontSize',16);

% Create title
title('Pressure vs. time','FontWeight','bold','FontSize',16);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','NorthWest');

