function createfigure_timeComp(X1, Y1, X2, YMatrix1)
%CREATEFIGURE(X1,Y1,X2,YMATRIX1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 03-Jul-2017 23:46:14

% Create figure
figure1 = figure('XVisual',...
    '0x22 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'FontWeight','bold','FontSize',16);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',4,'DisplayName','Ref. Sol.',...
    'Color',[0 0 0]);
size(X2)
size(YMatrix1)
% Create multiple lines using matrix input to plot
plot1 = plot(X2,YMatrix1,'Parent',axes1,'LineWidth',4);
set(plot1(1),'DisplayName','Forward Euler', 'Color', 'b', 'Marker','v');
set(plot1(2),'LineStyle',':','Marker','^','Markersize', 8,...
    'Color',[0.600000023841858 0.200000002980232 0],...
    'DisplayName',['Backward Euler ',sprintf('\n'),'\Delta t = O(\Delta x^2)']);
set(plot1(3),'LineStyle','-.','Marker','diamond',...
    'Color',[0.87058824300766 0.490196079015732 0],...
    'DisplayName',['Backward Euler ',sprintf('\n'),  '\Delta t = O(\Delta x)']);
set(plot1(4),'LineStyle','--','Marker','+',...
    'Color',[0.749019622802734 0 0.749019622802734],...
    'DisplayName','RK2 TVD');

% Create xlabel
xlabel('x','FontWeight','bold','FontSize',16);

% Create ylabel
ylabel('p','FontWeight','bold','FontSize',16);

% Create title
title('Solution profile as a function of x',...
    'FontWeight','bold',...
    'FontSize',16);

% Create legend
legend(axes1,'show');

