function createfiguretime(X1, Y1, X2, YMatrix1)
%CREATEFIGURE(X1,Y1,X2,YMATRIX1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 21-Mar-2017 13:26:55

% Create figure
figure1 = figure('XVisual',...
    '0x22 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'FontWeight','bold','FontSize',20); %16
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',6,'DisplayName','Ref. Sol.',...
    'Color',[0 0 0], 'LineStyle','--');
size(X2)
size(YMatrix1)
% Create multiple lines using matrix input to plot
plot1 = plot(X2,YMatrix1,'Parent',axes1,'LineWidth',4); %3 for pME
set(plot1(1),'LineStyle','-.','Color',[1 0 0],'DisplayName','Arithmetic');
set(plot1(2),'LineStyle','-','Color',[0 0 1],...
    'DisplayName','Harmonic');
set(plot1(3),'LineStyle',':','Color',[0 0.498039215803146 0],'DisplayName','Mod. Harmonic');

% Create ylabel
%ylabel('p(t, x = 0.12)','FontWeight','bold','FontSize',16);
ylabel('p','FontWeight','bold','FontSize',20);

% Create title
title('Solution profile as a function of t','FontWeight','bold','FontSize',20);

% Create xlabel
xlabel('t','FontWeight','bold','FontSize',20);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.719339622641509 0.173275388015212 0.171955403087479 0.131057919621749]);

