function createfigure_keff(X1,Y1,X2,Y2,Y3,X3,Y4,X4,Y5, X5)
%CREATEFIGURE(X1,Y1,X2,Y2,Y3,X3,Y4,X4,Y5)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  Y3:  vector of y data
%  X3:  vector of x data
%  Y4:  vector of y data
%  X4:  vector of x data
%  Y5:  vector of y data

%  Auto-generated by MATLAB on 18-May-2017 23:55:08

% Create figure
figure1 = figure('XVisual',...
    '0x22 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'FontWeight','bold','FontSize',16);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 1.01]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',5,'Color',[0 0.498039215803146 0],...
    'DisplayName','k^{eff}');

% Create plot
plot(X2,Y2,'Parent',axes1,'MarkerSize',35,'Marker','.','LineWidth',2,...
    'LineStyle','none',...
    'Color',[0.321568638086319 0.18823529779911 0.18823529779911],...
    'DisplayName','k_{min}');

% Create plot
plot(X5,Y3,'Parent',axes1,'MarkerSize',35,'Marker','.','LineWidth',2,...
    'LineStyle','none',...
    'Color',[1 0.400000005960464 0],...
    'DisplayName','k_{max}');

% Create plot
plot(X3,Y4,'Parent',axes1,'MarkerSize',35,'Marker','.','LineWidth',2,...
    'LineStyle','none',...
    'Color',[0 0 1],...
    'DisplayName','k^{harm}');

% Create plot
plot(X4,Y5,'Parent',axes1,'MarkerSize',35,'Marker','.','LineWidth',2,...
    'LineStyle','none',...
    'Color',[1 0 0],...
    'DisplayName','k^{arith}');

% Create xlabel
xlabel('\Delta x* / \Delta x','FontWeight','bold','FontSize',16);

% Create ylabel
ylabel('k_{eff}','FontWeight','bold','FontSize',16);

% Create title
title('Plot of k^{eff} vs. \Delta x* / \Delta x','FontWeight','bold',...
    'FontSize',16);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','NorthWest');

