function createfigureselfsharp(X1, YMatrix1, nolabel)
%CREATEFIGURE2(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 07-Jun-2017 23:18:50

% Create figure
figure1 = figure('XVisual',...
    '0x22 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'FontWeight','bold','FontSize',16);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',4);
set(plot1(1),'DisplayName','t = 0');
set(plot1(2),'LineStyle','--','Color',[1 0 0],'DisplayName','t = 0.02');
set(plot1(3),'LineStyle',':','Color',[0 0.498039215803146 0],...
    'DisplayName','t = 0.04');
set(plot1(4),'LineStyle','-.','DisplayName','t = 0.08','Color',[0 0 0]);

% Create title
if (~nolabel)
    title('Solution profile as a function of x','FontWeight','bold',...
    'FontSize',16);
end

% Create xlabel
xlabel('x','FontWeight','bold','FontSize',16);
if (nolabel)
     set(gca, 'Xtick', [])
     set(gca, 'Ytick', [])
%     % Create textarrow
%     % Create arrow
% annotation(figure1,'arrow',[0.687548942834769 0.756460454189507],...
%     [0.816725752508361 0.816053511705686],'LineWidth',2);
% 
% % Create textbox
% annotation(figure1,'textbox',...
%     [0.704210649960846 0.834448160535117 0.0342388410336725 0.0317725752508361],...
%     'String',{'t'},...
%     'HorizontalAlignment','center',...
%     'FontWeight','bold',...
%     'FontSize',16,...
%     'FitBoxToText','off',...
%     'LineStyle','none');
%   annotation(figure1,'textarrow',[0.680501174628035 0.744714173844949],...
%     [0.800003344481605 0.799331103678929],'TextEdgeColor','none',...
%     'TextLineWidth',2,...
%     'FontWeight','bold',...
%     'FontSize',16,...
%     'String',{'t'},...
%     'LineWidth',2);

end

% Create ylabel
ylabel('p','FontWeight','bold','FontSize',16);

% Create legend
if (~nolabel)
    legend(axes1,'show');
end

