function createfigure_temposcill(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 16-Jun-2017 19:03:13

% Create figure
figure1 = figure('XVisual',...
    '0x22 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,...
    'XTick',[0.1 0.12 0.14 0.16 0.18 0.2 0.22 0.24 0.26 0.28 0.3],...
    'FontWeight','bold',...
    'FontSize',16);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.1 0.3]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(1),'Marker','o','DisplayName','t = 0.020');
set(plot1(2),'Marker','square','DisplayName','t = 0.026');
set(plot1(3),'Marker','x','DisplayName','t = 0.032');
set(plot1(4),'Marker','^','DisplayName','t = 0.038');

% Create xlabel
xlabel('x','FontWeight','bold','FontSize',16);

% Create ylabel
ylabel('p','FontWeight','bold','FontSize',16);

% Create title
title('Solution profile as a function of x','FontWeight','bold',...
    'FontSize',16);

% Create legend
legend(axes1,'show');

